FROM php:8.1-apache

WORKDIR /var/www/html
 
COPY . /var/www/html
 
RUN apt-get update && apt-get install -y \
    libzip-dev \
    unzip \
    && docker-php-ext-install zip
 
RUN docker-php-ext-install pdo pdo_mysql mysqli
 
RUN a2enmod rewrite

EXPOSE 80
 
RUN chown -R www-data:www-data /var/www/html \
    && chmod -R 755 /var/www/html

CMD ["apache2-foreground"]
